name: Pull Upstream

on:
  schedule:
    - cron: "15 11 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.name "Midnightific"
          git config --global user.email "rbxmidnightific@gmail.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/rojo-rbx/rojo.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --no-edit || "The repo is already up to date!"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://Midnightific:${{ secrets.PAT }}@github.com/Midnightific/rojo.git master
